service: thinkphp51

provider:
  name: tencent
  runtime: Php7
  credentials: ~/credentials
  region: ap-shanghai

plugins:
  - serverless-tencent-scf

functions:
  thinkphp5:
    handler: tencent.main_handler
    memorySize: 128
    timeout: 600
    # events:
    #   - apigw:
    #       name: thinkphp5
    #       parameters:
    #         stageName: release
    #         serviceId:
    #         httpMethod: ANY
    #         path: /
    #         integratedResponse: true
    #         enableCORS: true
    #         serviceTimeout: 600

# you can overwrite defaults here
#  stage: dev
#  cosBucket: DEFAULT
#  role: QCS_SCFExcuteRole
#  memorySize: 256
#  timeout: 10
#  region: ap-shanghai
#  environment:
#    variables:
#      ENV_FIRST: env1
#      ENV_SECOND: env2
#  vpcConfig:
#    vpcId: test
#    subnetId: test

#    description: Tencent Serverless Cloud Function
#    runtime: Php7 # Php7 or Php5
#    memorySize: 256
#    timeout: 10
#    environment:
#      variables:
#        ENV_FIRST: env1
#        ENV_Third: env2
#    vpcConfig:
#      vpcId: test
#      subnetId: test
#    events:
#      - timer:
#          name: timer
#          parameters:
#            cronExpression: '*/5 * * * *'
#            enable: true
#      - cos:
#          name: cli-appid.cos.ap-beijing.myqcloud.com
#          parameters:
#            bucket: cli-appid.cos.ap-beijing.myqcloud.com
#            filter:
#              prefix: filterdir/
#              suffix: .jpg
#            events: cos:ObjectCreated:*
#            enable: true
#      - apigw:
#          name: hello_world_apigw
#          parameters:
#            stageName: release
#            serviceId:
#            httpMethod: ANY
#      - cmq:
#          name: cmq_trigger
#          parameters:
#            name: test-topic-queue
#            enable: true
#      - ckafka:
#          name: ckafka_trigger
#          parameters:
#            name: ckafka-2o10hua5
#            topic: test
#            maxMsgNum: 999
#            offset: latest
#            enable: true
